# Generated by Django 2.1.5 on 2019-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frstapp', '0002_auto_20190212_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
