# Generated by Django 2.1.5 on 2019-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frstapp', '0003_loginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
