# Generated by Django 2.1.5 on 2019-03-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0002_auto_20190308_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
